import React from "react";
import "./App.css";
import LazyLoad from "react-lazyload";
import MyLazyLoad from "./MyLazyLoad";

function App() {
  const LazyComponent = React.lazy(() => import("./MyComponent"));
  return (
    <>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <p>xxx</p>
      <MyLazyLoad>
        <img
          width="500"
          src="https://ginlon-bucket-01.oss-cn-shanghai.aliyuncs.com/2g8u7vdrtxg.jpg?Expires=1718512168&OSSAccessKeyId=TMP.3KhT3bLz91JwHFs8SixmCf5B8G3mruGHNsTqvEeqiK1sLUDpP2dschJbXFispim7nVHbaqw9aDh3jdaQ4RC8KPu22DGfNH&Signature=5WUedfr22uF3%2B4JhI5wrfV9UcM0%3D"
          alt=""
        />
      </MyLazyLoad>
      <MyLazyLoad placeholder={<div>loading...</div>} offset={200}>
        <LazyComponent />
      </MyLazyLoad>
    </>
  );
}

export default App;
